### ISSUE TITLE
Wrong material type

### ISSUE THREAD

**Issue by mobilpeter** [briis/pyaffalddk#3]
Logger: pyaffalddk.api
Kilde: custom_components/affalddk/__init__.py:123
integration: Affaldshåndtering DK (dokumentation, problemer)
Første forekomst: 9. maj 2024 kl. 17.40.12 (10 forekomster)
Senest logget: 06.15.13

Material type [240 l delt genbrug - grønt låg (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Vejen, Address ID: 17746
Material type [240 l genbrug - blåt låg (1 stk.)] is not defined in the system for Genbrug. Please notify the developer. Municipality: Vejen, Address ID: 17746

**Comment by mobilpeter** [comment]
Ja selvfølgelig, vi har følgende beholdere:

Grønt låg - PAP / PAPIR / METAL / GLAS

Blåt låg - PLAST / MAD & DRIKKEKARTONER

Sort låg - RESTAFFALD / MADAFFALD

Rød Miljøkasse - FARLIGT AFFALD

Mvh.

**Comment by briis** [comment]
De er nu alle fixet. Miljøkassen og Tekstil affald er dog ikke med, og det skyldes at de ikke automatisk afhentes, og derfor ikke har en tømningsdato.

Forventer jeg frigiver nu version i morgen, hvor disse rettelser er med.

**Comment by briis** [comment]
Lukker denne da den er fixet.
